name: Send Email on Push

on:
  push:
    branches:
      - main # אתה יכול לשנות את זה לענף אחר אם צריך

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "New Push to Repository: ${{ github.repository }}"
          to: "shoshani.ido@gmail.com"
          from: "shoshani.ido@gmail.com"
          body: |
            Branch: refs/heads/main
            Home:   https://github.com/${{ github.repository }}
            Commit: ${{ github.sha }}
                https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            Author: ${{ github.event.head_commit.committer.name }} <${{ github.event.head_commit.committer.email }}>
            Date:   ${{ github.event.head_commit.timestamp }}

            Changed paths:
            ${{ github.event.head_commit.modified }}  # This will show the changed paths, you can adjust if needed.

            Log Message:
            -----------
            ${{ github.event.head_commit.message }}
