name: Send Email on Push

on:
  push:
    branches:
      - main # תוכל לשנות את זה לענף אחר אם צריך

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "New Push to Repository: ${{ github.repository }}"
          to: "your-email@gmail.com"
          from: "your-email@gmail.com"
          body: |
            <h1>New Commit to Repository: ${{ github.repository }}</h1>
            <p><strong>Commit Message:</strong> ${{ github.event.head_commit.message }}</p>
            <p><strong>Author:</strong> ${{ github.event.head_commit.committer.name }}</p>
            <p><strong>Repository Name:</strong> ${{ github.repository }}</p>
            <p><strong>Commit SHA:</strong> ${{ github.sha }}</p>
